// LanguageContext.js
import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

const initialAudios = {
  'Português': {
    //Comidas
      'Abacate': require('../../assets/vozes/vozes_portugues/comidas/Abacate.mp3'),
      'Abacaxi': require('../../assets/vozes/vozes_portugues/comidas/Abacaxi.mp3'),
      'Banana': require('../../assets/vozes/vozes_portugues/comidas/Banana.mp3'),
      'Batata': require('../../assets/vozes/vozes_portugues/comidas/Batata.mp3'),
      'Brócolis': require('../../assets/vozes/vozes_portugues/comidas/Brócolis.mp3'),
      'Cenoura': require('../../assets/vozes/vozes_portugues/comidas/Cenoura.mp3'),
      'Coco': require('../../assets/vozes/vozes_portugues/comidas/Coco.mp3'),
      'Laranja': require('../../assets/vozes/vozes_portugues/comidas/Laranja.mp3'),
      'Leite': require('../../assets/vozes/vozes_portugues/comidas/Leite.mp3'),
      'Limão': require('../../assets/vozes/vozes_portugues/comidas/Limão.mp3'),
      'Maçã': require('../../assets/vozes/vozes_portugues/comidas/Maçã.mp3'),
      'Melancia': require('../../assets/vozes/vozes_portugues/comidas/Melancia.mp3'),
      'Morango': require('../../assets/vozes/vozes_portugues/comidas/Morango.mp3'),
      'Pão': require('../../assets/vozes/vozes_portugues/comidas/Pão.mp3'),
      'Queijo': require('../../assets/vozes/vozes_portugues/comidas/Queijo.mp3'),
      'Sanduíche': require('../../assets/vozes/vozes_portugues/comidas/Sanduíche.mp3'),
      'Sorvete': require('../../assets/vozes/vozes_portugues/comidas/Sorvete.mp3'),
      'Uva': require('../../assets/vozes/vozes_portugues/comidas/Uva.mp3'),
    //Alfabeto
      'A': require('../../assets/vozes/vozes_portugues/alfabeto/A.mp3'),
      'Be': require('../../assets/vozes/vozes_portugues/alfabeto/Be.mp3'),
      'Cê': require('../../assets/vozes/vozes_portugues/alfabeto/Cê.mp3'),
      'Dê': require('../../assets/vozes/vozes_portugues/alfabeto/Dê.mp3'),
      'É': require('../../assets/vozes/vozes_portugues/alfabeto/É.mp3'),
      'Efe': require('../../assets/vozes/vozes_portugues/alfabeto/Efe.mp3'),
      'Gê': require('../../assets/vozes/vozes_portugues/alfabeto/Gê.mp3'),
      'Agá': require('../../assets/vozes/vozes_portugues/alfabeto/Agá.mp3'),
      'i': require('../../assets/vozes/vozes_portugues/alfabeto/i.mp3'),
      'Jota': require('../../assets/vozes/vozes_portugues/alfabeto/Jota.mp3'),
      'Cá': require('../../assets/vozes/vozes_portugues/alfabeto/Cá.mp3'),
      'Ele': require('../../assets/vozes/vozes_portugues/alfabeto/Ele.mp3'),
      'Eme': require('../../assets/vozes/vozes_portugues/alfabeto/Eme.mp3'),
      'Ene': require('../../assets/vozes/vozes_portugues/alfabeto/Ene.mp3'),
      'Ó': require('../../assets/vozes/vozes_portugues/alfabeto/Ó.mp3'),
      'Pê': require('../../assets/vozes/vozes_portugues/alfabeto/Pê.mp3'),
      'Quê': require('../../assets/vozes/vozes_portugues/alfabeto/Quê.mp3'),
      'Erre': require('../../assets/vozes/vozes_portugues/alfabeto/Erre.mp3'),
      'Esse': require('../../assets/vozes/vozes_portugues/alfabeto/Esse.mp3'),
      'Tê': require('../../assets/vozes/vozes_portugues/alfabeto/Tê.mp3'),
      'U': require('../../assets/vozes/vozes_portugues/alfabeto/U.mp3'),
      'Vê': require('../../assets/vozes/vozes_portugues/alfabeto/Vê.mp3'),
      'Dáblio': require('../../assets/vozes/vozes_portugues/alfabeto/Dáblio.mp3'),
      'Xis': require('../../assets/vozes/vozes_portugues/alfabeto/Xis.mp3'),
      'Ipsilon': require('../../assets/vozes/vozes_portugues/alfabeto/Ipsilon.mp3'),
      'Zê': require('../../assets/vozes/vozes_portugues/alfabeto/Zê.mp3'),
    //Animais
      'Abelha': require('../../assets/vozes/vozes_portugues/animais/Abelha.mp3'),
      'Baleia': require('../../assets/vozes/vozes_portugues/animais/Baleia.mp3'),
      'Borboleta': require('../../assets/vozes/vozes_portugues/animais/Borboleta.mp3'),
      'Cachorro': require('../../assets/vozes/vozes_portugues/animais/Cachorro.mp3'),
      'Cavalo': require('../../assets/vozes/vozes_portugues/animais/Cavalo.mp3'),
      'Cobra': require('../../assets/vozes/vozes_portugues/animais/Cobra.mp3'),
      'Coelho': require('../../assets/vozes/vozes_portugues/animais/Coelho.mp3'),
      'Elefante': require('../../assets/vozes/vozes_portugues/animais/Elefante.mp3'),
      'Formiga': require('../../assets/vozes/vozes_portugues/animais/Formiga.mp3'),
      'Gato': require('../../assets/vozes/vozes_portugues/animais/Gato.mp3'),
      'Girafa': require('../../assets/vozes/vozes_portugues/animais/Girafa.mp3'),
      'Golfinho': require('../../assets/vozes/vozes_portugues/animais/Golfinho.mp3'),
      'Jacaré': require('../../assets/vozes/vozes_portugues/animais/Jacaré.mp3'),
      'Leão': require('../../assets/vozes/vozes_portugues/animais/Leão.mp3'),
      'Macaco': require('../../assets/vozes/vozes_portugues/animais/Macaco.mp3'),
      'Ovelha': require('../../assets/vozes/vozes_portugues/animais/Ovelha.mp3'),
      'Passarinho': require('../../assets/vozes/vozes_portugues/animais/Passarinho.mp3'),
      'Peixe': require('../../assets/vozes/vozes_portugues/animais/Peixe.mp3'),
      'Porco': require('../../assets/vozes/vozes_portugues/animais/Porco.mp3'),
      'Rato': require('../../assets/vozes/vozes_portugues/animais/Rato.mp3'),
      'Sapo': require('../../assets/vozes/vozes_portugues/animais/Sapo.mp3'),
      'Tartaruga': require('../../assets/vozes/vozes_portugues/animais/Tartaruga.mp3'),
      'Urso': require('../../assets/vozes/vozes_portugues/animais/Urso.mp3'),
      'Vaca': require('../../assets/vozes/vozes_portugues/animais/Vaca.mp3'),
    //Cores
      'Amarelo': require('../../assets/vozes/vozes_portugues/cores/Amarelo.mp3'),
      'Azul': require('../../assets/vozes/vozes_portugues/cores/Azul.mp3'),
      'Branco': require('../../assets/vozes/vozes_portugues/cores/Branco.mp3'),
      'Cinza': require('../../assets/vozes/vozes_portugues/cores/Cinza.mp3'),
      'Laranja': require('../../assets/vozes/vozes_portugues/cores/Laranja.mp3'),
      'Marrom': require('../../assets/vozes/vozes_portugues/cores/Marrom.mp3'),
      'Preto': require('../../assets/vozes/vozes_portugues/cores/Preto.mp3'),
      'Rosa': require('../../assets/vozes/vozes_portugues/cores/Rosa.mp3'),
      'Roxo': require('../../assets/vozes/vozes_portugues/cores/Roxo.mp3'),
      'Verde': require('../../assets/vozes/vozes_portugues/cores/Verde.mp3'),
      'Vermelho': require('../../assets/vozes/vozes_portugues/cores/Vermelho.mp3'),
      'Violeta': require('../../assets/vozes/vozes_portugues/cores/Violeta.mp3'),
    //Numeros
      'Zero': require('../../assets/vozes/vozes_portugues/numeros/Zero.mp3'),
      'Um': require('../../assets/vozes/vozes_portugues/numeros/Um.mp3'),
      'Dois': require('../../assets/vozes/vozes_portugues/numeros/Dois.mp3'),
      'Três': require('../../assets/vozes/vozes_portugues/numeros/Três.mp3'),
      'Quatro': require('../../assets/vozes/vozes_portugues/numeros/Quatro.mp3'),
      'Cinco': require('../../assets/vozes/vozes_portugues/numeros/Cinco.mp3'),
      'Seis': require('../../assets/vozes/vozes_portugues/numeros/Seis.mp3'),
      'Sete': require('../../assets/vozes/vozes_portugues/numeros/Sete.mp3'),
      'Oito': require('../../assets/vozes/vozes_portugues/numeros/Oito.mp3'),
      'Nove': require('../../assets/vozes/vozes_portugues/numeros/Nove.mp3'),
      'Dez': require('../../assets/vozes/vozes_portugues/numeros/Dez.mp3'),
//Partes do corpo
      'Barriga': require('../../assets/vozes/vozes_portugues/partes do corpo/Barriga.mp3'),
      'Boca': require('../../assets/vozes/vozes_portugues/partes do corpo/Boca.mp3'),
      'Cabeça': require('../../assets/vozes/vozes_portugues/partes do corpo/Cabeça.mp3'),
      'Cabelo': require('../../assets/vozes/vozes_portugues/partes do corpo/Cabelo.mp3'),
      'Mão': require('../../assets/vozes/vozes_portugues/partes do corpo/Mão.mp3'),
      'Menina': require('../../assets/vozes/vozes_portugues/partes do corpo/Menina.mp3'),
      'Menino': require('../../assets/vozes/vozes_portugues/partes do corpo/Menino.mp3'),
      'Nariz': require('../../assets/vozes/vozes_portugues/partes do corpo/Nariz.mp3'),
      'Olhos': require('../../assets/vozes/vozes_portugues/partes do corpo/Olhos.mp3'),
      'Ouvido': require('../../assets/vozes/vozes_portugues/partes do corpo/Ouvido.mp3'),
      'Pé': require('../../assets/vozes/vozes_portugues/partes do corpo/Pé.mp3'),
      'Perna': require('../../assets/vozes/vozes_portugues/partes do corpo/Perna.mp3'),
      

    },
    'Inglês': {
      'Avocado': require('../../assets/vozes/vozes_inglês/food/Avocado.mp3'),
      'Pineapple': require('../../assets/vozes/vozes_inglês/food/Pineapple.mp3'),
      'Banana': require('../../assets/vozes/vozes_inglês/food/Banana.mp3'),
      'Potato': require('../../assets/vozes/vozes_inglês/food/Potato.mp3'),
      'Broccoli': require('../../assets/vozes/vozes_inglês/food/Broccoli.mp3'),
      'Carrot': require('../../assets/vozes/vozes_inglês/food/Carrot.mp3'),
      'Coconut': require('../../assets/vozes/vozes_inglês/food/Coconut.mp3'),
      'Orange': require('../../assets/vozes/vozes_inglês/food/Orange.mp3'),
      'Milk': require('../../assets/vozes/vozes_inglês/food/Milk.mp3'),
      'Lemon': require('../../assets/vozes/vozes_inglês/food/Lemon.mp3'),
      'Apple': require('../../assets/vozes/vozes_inglês/food/Apple.mp3'),
      'Watermelon': require('../../assets/vozes/vozes_inglês/food/Watermelon.mp3'),
      'Strawberry': require('../../assets/vozes/vozes_inglês/food/Strawberry.mp3'),
      'Bread': require('../../assets/vozes/vozes_inglês/food/Bread.mp3'),
      'Cheese': require('../../assets/vozes/vozes_inglês/food/Cheese.mp3'),
      'Sandwich': require('../../assets/vozes/vozes_inglês/food/Sandwich.mp3'),
      'Ice Cream': require('../../assets/vozes/vozes_inglês/food/Ice Cream.mp3'),
      'Grape': require('../../assets/vozes/vozes_inglês/food/Grape.mp3'),
 // Adicione os demais áudios
      'Êi': require('../../assets/vozes/vozes_inglês/alphabet/Êi.mp3'),
      'Bí': require('../../assets/vozes/vozes_inglês/alphabet/Bí.mp3'),
      'Cí': require('../../assets/vozes/vozes_inglês/alphabet/Cí.mp3'),
      'Dí': require('../../assets/vozes/vozes_inglês/alphabet/Dí.mp3'),
      'Íh': require('../../assets/vozes/vozes_inglês/alphabet/Íh.mp3'),
      'Éf': require('../../assets/vozes/vozes_inglês/alphabet/Éf.mp3'),
      'Dgí': require('../../assets/vozes/vozes_inglês/alphabet/Dgí.mp3'),
      'Êitch': require('../../assets/vozes/vozes_inglês/alphabet/Êitch.mp3'),
      'Ái': require('../../assets/vozes/vozes_inglês/alphabet/Ái.mp3'),
      'Djêi': require('../../assets/vozes/vozes_inglês/alphabet/Djêi.mp3'),
      'Kêi': require('../../assets/vozes/vozes_inglês/alphabet/Kêi.mp3'),
      'Él': require('../../assets/vozes/vozes_inglês/alphabet/Él.mp3'),
      'Êm': require('../../assets/vozes/vozes_inglês/alphabet/Êm.mp3'),
      'Ên': require('../../assets/vozes/vozes_inglês/alphabet/Ên.mp3'),
      'Ôu': require('../../assets/vozes/vozes_inglês/alphabet/Ôu.mp3'),
      'Pí': require('../../assets/vozes/vozes_inglês/alphabet/Pí.mp3'),
      'Kíu': require('../../assets/vozes/vozes_inglês/alphabet/Kíu.mp3'),
      'Ár': require('../../assets/vozes/vozes_inglês/alphabet/Ár.mp3'),
      'És': require('../../assets/vozes/vozes_inglês/alphabet/És.mp3'),
      'Tí': require('../../assets/vozes/vozes_inglês/alphabet/Tí.mp3'),
      'You': require('../../assets/vozes/vozes_inglês/alphabet/You.mp3'),
      'Ví': require('../../assets/vozes/vozes_inglês/alphabet/Ví.mp3'),
      'Dãbouyou': require('../../assets/vozes/vozes_inglês/alphabet/Dãbouyou.mp3'),
      'Éks': require('../../assets/vozes/vozes_inglês/alphabet/Éks.mp3'),
      'Uái': require('../../assets/vozes/vozes_inglês/alphabet/Uái.mp3'),
      'Zí': require('../../assets/vozes/vozes_inglês/alphabet/Zí.mp3'),
      //  
      'Bee': require('../../assets/vozes/vozes_inglês/animals/Bee.mp3'),
      'Whale': require('../../assets/vozes/vozes_inglês/animals/Whale.mp3'),
      'Butterfly': require('../../assets/vozes/vozes_inglês/animals/Butterfly.mp3'),
      'Dog': require('../../assets/vozes/vozes_inglês/animals/Dog.mp3'),
      'Horse': require('../../assets/vozes/vozes_inglês/animals/Horse.mp3'),
      'Snake': require('../../assets/vozes/vozes_inglês/animals/Snake.mp3'),
      'Rabbit': require('../../assets/vozes/vozes_inglês/animals/Rabbit.mp3'),
      'Elephant': require('../../assets/vozes/vozes_inglês/animals/Elephant.mp3'),
      'Ant': require('../../assets/vozes/vozes_inglês/animals/Ant.mp3'),
      'Cat': require('../../assets/vozes/vozes_inglês/animals/Cat.mp3'),
      'Giraffe': require('../../assets/vozes/vozes_inglês/animals/Giraffe.mp3'),
      'Dolphin': require('../../assets/vozes/vozes_inglês/animals/Dolphin.mp3'),
      'Alligator': require('../../assets/vozes/vozes_inglês/animals/Alligator.mp3'),
      'Lion': require('../../assets/vozes/vozes_inglês/animals/Lion.mp3'),
      'Monkey': require('../../assets/vozes/vozes_inglês/animals/Monkey.mp3'),
      'Sheep': require('../../assets/vozes/vozes_inglês/animals/Sheep.mp3'),
      'Bird': require('../../assets/vozes/vozes_inglês/animals/Bird.mp3'),
      'Fish': require('../../assets/vozes/vozes_inglês/animals/fish.mp3'),
      'Pig': require('../../assets/vozes/vozes_inglês/animals/Pig.mp3'),
      'Mouse': require('../../assets/vozes/vozes_inglês/animals/Mouse.mp3'),
      'Frog': require('../../assets/vozes/vozes_inglês/animals/Frog.mp3'),
      'Turtle': require('../../assets/vozes/vozes_inglês/animals/Turtle.mp3'),
      'Bear': require('../../assets/vozes/vozes_inglês/animals/Bear.mp3'),
      'Cow': require('../../assets/vozes/vozes_inglês/animals/Cow.mp3'),
// Colors
      'Yellow': require('../../assets/vozes/vozes_inglês/colors/Yellow.mp3'),
      'Blue': require('../../assets/vozes/vozes_inglês/colors/Blue.mp3'),
      'White': require('../../assets/vozes/vozes_inglês/colors/White.mp3'),
      'Gray': require('../../assets/vozes/vozes_inglês/colors/Gray.mp3'),
      'Orange': require('../../assets/vozes/vozes_inglês/colors/Orange.mp3'),
      'Brown': require('../../assets/vozes/vozes_inglês/colors/Brown.mp3'),
      'Black': require('../../assets/vozes/vozes_inglês/colors/Black.mp3'),
      'Pink': require('../../assets/vozes/vozes_inglês/colors/Pink.mp3'),
      'Purple': require('../../assets/vozes/vozes_inglês/colors/Purple.mp3'),
      'Green': require('../../assets/vozes/vozes_inglês/colors/Green.mp3'),
      'Red': require('../../assets/vozes/vozes_inglês/colors/Red.mp3'),
      'Violet': require('../../assets/vozes/vozes_inglês/colors/Violet.mp3'),

      'Zero': require('../../assets/vozes/vozes_inglês/numbers/Zero.mp3'),
      'One': require('../../assets/vozes/vozes_inglês/numbers/One.mp3'),
      'Two': require('../../assets/vozes/vozes_inglês/numbers/Two.mp3'),
      'Three': require('../../assets/vozes/vozes_inglês/numbers/Three.mp3'),
      'Four': require('../../assets/vozes/vozes_inglês/numbers/Four.mp3'),
      'Five': require('../../assets/vozes/vozes_inglês/numbers/Five.mp3'),
      'Six': require('../../assets/vozes/vozes_inglês/numbers/Six.mp3'),
      'Seven': require('../../assets/vozes/vozes_inglês/numbers/Seven.mp3'),
      'Eight': require('../../assets/vozes/vozes_inglês/numbers/Eight.mp3'),
      'Nine': require('../../assets/vozes/vozes_inglês/numbers/Nine.mp3'),
      'Ten': require('../../assets/vozes/vozes_inglês/numbers/Ten.mp3'),    
    //Partes do corpo
      'Stomach': require('../../assets/vozes/vozes_inglês/body Parts/Stomach.mp3'),
      'Mouth': require('../../assets/vozes/vozes_inglês/body Parts/Mouth.mp3'),
      'Head': require('../../assets/vozes/vozes_inglês/body Parts/Head.mp3'),
      'Hair': require('../../assets/vozes/vozes_inglês/body Parts/Hair.mp3'),
      'Hand': require('../../assets/vozes/vozes_inglês/body Parts/Hand.mp3'),
      'Girl': require('../../assets/vozes/vozes_inglês/body Parts/Girl.mp3'),
      'Boy': require('../../assets/vozes/vozes_inglês/body Parts/Boy.mp3'),
      'Nose': require('../../assets/vozes/vozes_inglês/body Parts/Nose.mp3'),
      'Eyes': require('../../assets/vozes/vozes_inglês/body Parts/Eyes.mp3'),
      'Ear': require('../../assets/vozes/vozes_inglês/body Parts/Ear.mp3'),
      'Foot': require('../../assets/vozes/vozes_inglês/body Parts/Foot.mp3'),
      'Leg': require('../../assets/vozes/vozes_inglês/body Parts/Leg.mp3'),
    },
    'Espanhol': {
      'Aguacate': require('../../assets/vozes/vozes_espanhol/alimentos/Aguacate.mp3'),
      'Piña': require('../../assets/vozes/vozes_espanhol/alimentos/Piña.mp3'),
      'Plátano': require('../../assets/vozes/vozes_espanhol/alimentos/Plátano.mp3'),
      'Papa': require('../../assets/vozes/vozes_espanhol/alimentos/Papa.mp3'),
      'Brócoli': require('../../assets/vozes/vozes_espanhol/alimentos/Brócoli.mp3'),
      'Zanahoria': require('../../assets/vozes/vozes_espanhol/alimentos/Zanahoria.mp3'),
      'Coco': require('../../assets/vozes/vozes_espanhol/alimentos/Coco.mp3'),
      'Naranja': require('../../assets/vozes/vozes_espanhol/alimentos/Naranja.mp3'),
      'Leche': require('../../assets/vozes/vozes_espanhol/alimentos/Leche.mp3'),
      'Limón': require('../../assets/vozes/vozes_espanhol/alimentos/Limón.mp3'),
      'Manzana': require('../../assets/vozes/vozes_espanhol/alimentos/Manzana.mp3'),
      'Sandía': require('../../assets/vozes/vozes_espanhol/alimentos/Sandía.mp3'),
      'Frutilla': require('../../assets/vozes/vozes_espanhol/alimentos/Frutilla.mp3'),
      'Pan': require('../../assets/vozes/vozes_espanhol/alimentos/Pan.mp3'),
      'Queso': require('../../assets/vozes/vozes_espanhol/alimentos/Queso.mp3'),
      'Sándwich': require('../../assets/vozes/vozes_espanhol/alimentos/Sándwich.mp3'),
      'Helado': require('../../assets/vozes/vozes_espanhol/alimentos/Helado.mp3'),
      'Uva': require('../../assets/vozes/vozes_espanhol/alimentos/Uva.mp3'),
//Adicione os demais áudios
      'A': require('../../assets/vozes/vozes_espanhol/alfabeto/A.mp3'),
      'Be': require('../../assets/vozes/vozes_espanhol/alfabeto/Be.mp3'),
      'Ce': require('../../assets/vozes/vozes_espanhol/alfabeto/Ce.mp3'),
      'De': require('../../assets/vozes/vozes_espanhol/alfabeto/De.mp3'),
      'E': require('../../assets/vozes/vozes_espanhol/alfabeto/E.mp3'),
      'Efe': require('../../assets/vozes/vozes_espanhol/alfabeto/Efe.mp3'),
      'Ge': require('../../assets/vozes/vozes_espanhol/alfabeto/Ge.mp3'),
      'Hache': require('../../assets/vozes/vozes_espanhol/alfabeto/Hache.mp3'),
      'i': require('../../assets/vozes/vozes_espanhol/alfabeto/i.mp3'),
      'Jota': require('../../assets/vozes/vozes_espanhol/alfabeto/Jota.mp3'),
      'Ka': require('../../assets/vozes/vozes_espanhol/alfabeto/Ka.mp3'),
      'Ele': require('../../assets/vozes/vozes_espanhol/alfabeto/Ele.mp3'),
      'Eme': require('../../assets/vozes/vozes_espanhol/alfabeto/Eme.mp3'),
      'Ene': require('../../assets/vozes/vozes_espanhol/alfabeto/Ene.mp3'),
      'O': require('../../assets/vozes/vozes_espanhol/alfabeto/O.mp3'),
      'Pe': require('../../assets/vozes/vozes_espanhol/alfabeto/Pe.mp3'),
      'Cu': require('../../assets/vozes/vozes_espanhol/alfabeto/Cu.mp3'),
      'Erre': require('../../assets/vozes/vozes_espanhol/alfabeto/Erre.mp3'),
      'Esse': require('../../assets/vozes/vozes_espanhol/alfabeto/Ese.mp3'),
      'Te': require('../../assets/vozes/vozes_espanhol/alfabeto/Te.mp3'),
      'U': require('../../assets/vozes/vozes_espanhol/alfabeto/U.mp3'),
      'Uve': require('../../assets/vozes/vozes_espanhol/alfabeto/Uve.mp3'),
      'Double Uve': require('../../assets/vozes/vozes_espanhol/alfabeto/Double uve.mp3'),
      'Équis': require('../../assets/vozes/vozes_espanhol/alfabeto/Équis.mp3'),
      'Ye': require('../../assets/vozes/vozes_espanhol/alfabeto/Ye.mp3'),
      'Zeta': require('../../assets/vozes/vozes_espanhol/alfabeto/Zeta.mp3'),
      //
      'Abeja': require('../../assets/vozes/vozes_espanhol/animales/Abeja.mp3'),
      'Ballena': require('../../assets/vozes/vozes_espanhol/animales/Ballena.mp3'),
      'Mariposa': require('../../assets/vozes/vozes_espanhol/animales/Mariposa.mp3'),
      'Perro': require('../../assets/vozes/vozes_espanhol/animales/Perro.mp3'),
      'Caballo': require('../../assets/vozes/vozes_espanhol/animales/Caballo.mp3'),
      'Serpiente': require('../../assets/vozes/vozes_espanhol/animales/Serpiente.mp3'),
      'Conejo': require('../../assets/vozes/vozes_espanhol/animales/Conejo.mp3'),
      'Elefante': require('../../assets/vozes/vozes_espanhol/animales/Elefante.mp3'),
      'Hormiga': require('../../assets/vozes/vozes_espanhol/animales/Hormiga.mp3'),
      'Gato': require('../../assets/vozes/vozes_espanhol/animales/Gato.mp3'),
      'Jirafa': require('../../assets/vozes/vozes_espanhol/animales/Jirafa.mp3'),
      'Delfín': require('../../assets/vozes/vozes_espanhol/animales/Delfín.mp3'),
      'Caimán': require('../../assets/vozes/vozes_espanhol/animales/Caimán.mp3'),
      'León': require('../../assets/vozes/vozes_espanhol/animales/León.mp3'),
      'Mono': require('../../assets/vozes/vozes_espanhol/animales/Mono.mp3'),
      'Oveja': require('../../assets/vozes/vozes_espanhol/animales/Oveja.mp3'),
      'Pájaro': require('../../assets/vozes/vozes_espanhol/animales/Pájaro.mp3'),
      'Pez': require('../../assets/vozes/vozes_espanhol/animales/Pez.mp3'),
      'Chancho': require('../../assets/vozes/vozes_espanhol/animales/Chancho.mp3'),
      'Ratón': require('../../assets/vozes/vozes_espanhol/animales/Ratón.mp3'),
      'Rana': require('../../assets/vozes/vozes_espanhol/animales/Rana.mp3'),
      'Tortuga': require('../../assets/vozes/vozes_espanhol/animales/Tortuga.mp3'),
      'Oso': require('../../assets/vozes/vozes_espanhol/animales/Oso.mp3'),
      'Vaca': require('../../assets/vozes/vozes_espanhol/animales/Vaca.mp3'),
// Colores
      'Amarillo': require('../../assets/vozes/vozes_espanhol/colores/Amarillo.mp3'),
      'Azul': require('../../assets/vozes/vozes_espanhol/colores/Azul.mp3'),
      'Blanco': require('../../assets/vozes/vozes_espanhol/colores/Blanco.mp3'),
      'Gris': require('../../assets/vozes/vozes_espanhol/colores/Gris.mp3'),
      'Naranja': require('../../assets/vozes/vozes_espanhol/colores/Naranja.mp3'),
      'Marrón': require('../../assets/vozes/vozes_espanhol/colores/Marrón.mp3'),
      'Negro': require('../../assets/vozes/vozes_espanhol/colores/Negro.mp3'),
      'Rosa': require('../../assets/vozes/vozes_espanhol/colores/Rosa.mp3'),
      'Morado': require('../../assets/vozes/vozes_espanhol/colores/Morado.mp3'),
      'Verde': require('../../assets/vozes/vozes_espanhol/colores/Verde.mp3'),
      'Rojo': require('../../assets/vozes/vozes_espanhol/colores/Rojo.mp3'),
      'Violeta': require('../../assets/vozes/vozes_espanhol/colores/Violeta.mp3'),
//Numeros
      'Cero': require('../../assets/vozes/vozes_espanhol/numeros/Cero.mp3'),
      'Uno': require('../../assets/vozes/vozes_espanhol/numeros/Uno.mp3'),
      'Dos': require('../../assets/vozes/vozes_espanhol/numeros/Dos.mp3'),
      'Tres': require('../../assets/vozes/vozes_espanhol/numeros/Tres.mp3'),
      'Cuatro': require('../../assets/vozes/vozes_espanhol/numeros/Cuatro.mp3'),
      'Cinco': require('../../assets/vozes/vozes_espanhol/numeros/Cinco.mp3'),
      'Seis': require('../../assets/vozes/vozes_espanhol/numeros/Seis.mp3'),
      'Siete': require('../../assets/vozes/vozes_espanhol/numeros/Siete.mp3'),
      'Ocho': require('../../assets/vozes/vozes_espanhol/numeros/Ocho.mp3'),
      'Nueve': require('../../assets/vozes/vozes_espanhol/numeros/Nueve.mp3'),
      'Diez': require('../../assets/vozes/vozes_espanhol/numeros/Diez.mp3'),    
    //Partes do corpo
      'Barriga': require('../../assets/vozes/vozes_espanhol/partes del cuerpo/Barriga.mp3'),
      'Boca': require('../../assets/vozes/vozes_espanhol/partes del cuerpo/Boca.mp3'),
      'Cabeza': require('../../assets/vozes/vozes_espanhol/partes del cuerpo/Cabeza.mp3'),
      'Pelo': require('../../assets/vozes/vozes_espanhol/partes del cuerpo/Pelo.mp3'),
      'Mano': require('../../assets/vozes/vozes_espanhol/partes del cuerpo/Mano.mp3'),
      'Niña': require('../../assets/vozes/vozes_espanhol/partes del cuerpo/Niña.mp3'),
      'Niño': require('../../assets/vozes/vozes_espanhol/partes del cuerpo/Niño.mp3'),
      'Nariz': require('../../assets/vozes/vozes_espanhol/partes del cuerpo/Nariz.mp3'),
      'Ojos': require('../../assets/vozes/vozes_espanhol/partes del cuerpo/Ojos.mp3'),
      'Oreja': require('../../assets/vozes/vozes_espanhol/partes del cuerpo/Oreja.mp3'),
      'Pie': require('../../assets/vozes/vozes_espanhol/partes del cuerpo/Pie.mp3'),
      'Pierna': require('../../assets/vozes/vozes_espanhol/partes del cuerpo/Pierna.mp3'),
      },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('Português');
  const [audios, setAudios] = useState(initialAudios);

  const changeLanguage = (lang) => {
    setLanguage(lang);
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, audios }}>
      {children}
    </LanguageContext.Provider>
  );
};
